name: notifications
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  awesome_notifications: ^0.10.1
  cool_alert: ^2.0.1
  awesome_notifications_core: ^0.10.1
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/image.png"
  adaptive_icon_background: "#6C63FF"
  adaptive_icon_foreground: "assets/image.png"

flutter:
  uses-material-design: true

  assets:
    - assets/image.png
